# Generated by Django 5.0.6 on 2024-07-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCombustible', models.CharField(max_length=3)),
                ('LitrosCombustible', models.CharField(max_length=50)),
                ('FechaProduccion', models.CharField(max_length=50)),
                ('DefinirTurno', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('AM', 'AM')], max_length=50)),
                ('Horaregistro', models.CharField(max_length=300)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
