# Generated by Django 5.0.6 on 2024-07-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registro_ultimaedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='UltimaEdicion',
        ),
    ]
