# Generated by Django 5.0.6 on 2024-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registro_definirturno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='UltimaEdicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
